# Generated by Django 4.2.30 on 2026-09-11 13:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=1000)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('spotify', 'Spotify'), ('generic', 'Generic / Other')], default='generic', max_length=30)),
                ('media_type', models.CharField(default='video', max_length=20)),
                ('format_id', models.CharField(blank=True, default='best', max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=1500)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('processing', 'Processing / Converting'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('progress', models.FloatField(default=0.0)),
                ('progress_message', models.CharField(blank=True, default='Task initialized', max_length=255)),
                ('file_path', models.CharField(blank=True, default='', max_length=1000)),
                ('file_name', models.CharField(blank=True, default='', max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaInfoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('platform', models.CharField(max_length=30)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
